/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer Swift 3
 */
public class EditNilai extends javax.swing.JFrame {

    /**
     * Creates new form EditDataSiswa
     */
    public EditNilai() {
        initComponents();
        tampil_combo();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jLabelNama = new javax.swing.JLabel();
        jTextFieldNama = new javax.swing.JTextField();
        jLabelKelas = new javax.swing.JLabel();
        jTextFieldIpa = new javax.swing.JTextField();
        jLabelNoTelp = new javax.swing.JLabel();
        jTextFieldIps = new javax.swing.JTextField();
        jLabelAlamat = new javax.swing.JLabel();
        jButtonSubmit = new javax.swing.JButton();
        jComboBoxId = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jTextFieldMtk = new javax.swing.JTextField();
        jLabelBahasa = new javax.swing.JLabel();
        jTextFieldBahasa = new javax.swing.JTextField();
        jLabelEnglish = new javax.swing.JLabel();
        jTextFieldEnglish = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Form Edit Nilai");

        jLabelId.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelId.setText("ID");

        jLabelNama.setText("Nama : ");

        jTextFieldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNamaActionPerformed(evt);
            }
        });

        jLabelKelas.setText("IPA");

        jLabelNoTelp.setText("IPS");

        jLabelAlamat.setText("MATEMATIKA");

        jButtonSubmit.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonSubmit.setText("Update");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });

        jComboBoxId.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-pilih ID-" }));
        jComboBoxId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxIdActionPerformed(evt);
            }
        });

        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabelBahasa.setText("BAHASA");

        jLabelEnglish.setText("ENGLISH");
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonSubmit)
                .addGap(46, 46, 46)
                .addComponent(jButton1)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelId)
                            .addComponent(jLabelKelas)
                            .addComponent(jLabelNoTelp)
                            .addComponent(jLabelAlamat)
                            .addComponent(jLabelBahasa)
                            .addComponent(jLabelEnglish))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelNama)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldEnglish, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldBahasa, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldMtk, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldIpa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                .addComponent(jTextFieldIps, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelId)
                    .addComponent(jComboBoxId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNama)
                    .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabelKelas))
                    .addComponent(jTextFieldIpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNoTelp)
                    .addComponent(jTextFieldIps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAlamat)
                    .addComponent(jTextFieldMtk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBahasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBahasa))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEnglish)
                    .addComponent(jTextFieldEnglish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSubmit)
                    .addComponent(jButton1))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void tampil_combo()
    {
        try {
        Connection c = KoneksiDatabase.getKoneksi();
        Statement s = c.createStatement();
        String sql = "select id from nilai order by id asc";      // disini saya menampilkan NIM, anda dapat menampilkan
        ResultSet res = s.executeQuery(sql);                                // yang anda ingin kan
        
        while(res.next()){
            Object[] ob = new Object[6];
            ob[0] = res.getString(1);
            
            jComboBoxId.addItem(ob[0]);                                      // fungsi ini bertugas menampung isi dari database
        }
        res.close(); s.close();
         
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    public void tampilnama()
    {
        try {
        Connection c = KoneksiDatabase.getKoneksi();
        Statement s = c.createStatement();
        String sql = "select nama from siswa where id='"+jComboBoxId.getSelectedItem()+"'";  
        ResultSet res = s.executeQuery(sql);
        
        while(res.next()){
            Object[] ob = new Object[5];
            ob[0]=  res.getString(1);//nama
//            ob[1]= res.getString(2);//ipa
//            ob[2]= res.getString(3);//ips
//            ob[3]= res.getString(4);//bahasa
//            ob[4]= res.getString(5);//english
            
            
            jTextFieldNama.setText((String) ob[0]);
//            jTextFieldIps.setText((String) ob[1]);
//            jTextFieldMtk.setText((String) ob[2]);
//            jTextFieldBahasa.setText((String) ob[3]);
//            jTextFieldEnglish.setText((String) ob[4]);
        }
        res.close(); s.close();
         
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }              
    }
    public void tampil()
    {
        try {
        Connection c = KoneksiDatabase.getKoneksi();
        Statement s = c.createStatement();
        String sql = "select ipa, ips, mtk,bahasa,english from nilai where id='"+jComboBoxId.getSelectedItem()+"'";  
        ResultSet res = s.executeQuery(sql);
        
        while(res.next()){
            Object[] ob = new Object[5];
            ob[0]=  res.getString(1);//nama
            ob[1]= res.getString(2);//ipa
            ob[2]= res.getString(3);//ips
            ob[3]= res.getString(4);//bahasa
            ob[4]= res.getString(5);//english
            
            
            jTextFieldIpa.setText((String) ob[0]);
            jTextFieldIps.setText((String) ob[1]);
            jTextFieldMtk.setText((String) ob[2]);
            jTextFieldBahasa.setText((String) ob[3]);
            jTextFieldEnglish.setText((String) ob[4]);
        }
        res.close(); s.close();
         
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }              
    }
    private void DeleteData() {
    
    String sql = "DELETE FROM nilai WHERE id='" + jComboBoxId.getSelectedItem() + "'";
    try {
        Connection c = KoneksiDatabase.getKoneksi();
        Statement s = c.createStatement();
        s.executeUpdate(sql);
    } catch (Exception e) {
        System.out.println("Terjadi kesalahan, karena " + e.getMessage());
        JOptionPane.showMessageDialog(null, "Terjadi kesalahan, karena " + e.getMessage());
    }
}
    
    private void jTextFieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNamaActionPerformed

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        // TODO add your handling code here:
        try {
            Connection c = KoneksiDatabase.getKoneksi();
             Statement s = c.createStatement();
             //String sql = "UPDATE siswa SET nama='" + jTextFieldNama.getText() + "',kelas='" + jTextFieldKelas.getText() + "',WHERE id_barang='" + idBarang + "'";
             String sql = "update nilai SET "
                     + "ipa='"+this.jTextFieldIpa.getText()+"'"
                     + ",ips='"+this.jTextFieldIps.getText()+"'"
                     + ",mtk='"+this.jTextFieldMtk.getText()+"'"
                     + ",bahasa='"+this.jTextFieldBahasa.getText()+"'"
                     + ",english='"+this.jTextFieldEnglish.getText()+"'"
                     + "where id='"+this.jComboBoxId.getSelectedItem()+"'";
             PreparedStatement mStatement = (PreparedStatement) c.prepareStatement(sql);
             mStatement.executeUpdate();
             mStatement.close();
            JOptionPane.showMessageDialog(this, "Data berhasil diupdate");
            
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "terjadi kesalahan"+ex.getMessage());
        }
       
    }//GEN-LAST:event_jButtonSubmitActionPerformed

    private void jComboBoxIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxIdActionPerformed
        // TODO add your handling code here:
        tampil();
        tampilnama();
    }//GEN-LAST:event_jComboBoxIdActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int hasil = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin akan menghapus data dengan id " + jComboBoxId.getSelectedItem(), null, JOptionPane.YES_NO_OPTION);
        if (hasil == JOptionPane.YES_OPTION) {
            DeleteData();
            new LihatNilaiAdmin().show();
            
            JOptionPane.showMessageDialog(null, "Data telah berhasil dihapus!");
        } else if (hasil == JOptionPane.NO_OPTION) {
           JOptionPane.showMessageDialog(null, "Data batal dihapus!");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditNilai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JComboBox jComboBoxId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAlamat;
    private javax.swing.JLabel jLabelBahasa;
    private javax.swing.JLabel jLabelEnglish;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelKelas;
    private javax.swing.JLabel jLabelNama;
    private javax.swing.JLabel jLabelNoTelp;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField jTextFieldBahasa;
    private javax.swing.JTextField jTextFieldEnglish;
    private javax.swing.JTextField jTextFieldIpa;
    private javax.swing.JTextField jTextFieldIps;
    private javax.swing.JTextField jTextFieldMtk;
    private javax.swing.JTextField jTextFieldNama;
    // End of variables declaration//GEN-END:variables
}
